<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ecl="urn:easee-gas.eu:edigas:codelistsV6" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<!-- import the codelsits -->
	<xsd:import namespace="urn:easee-gas.eu:edigas:codelistsV6" schemaLocation="../cclib-v6/urn-easee-gas-eu-edigas-codelistsV6.xsd"/>
	<!-- include the local message restrictions -->
	<xsd:include schemaLocation="urn-easee-gas-eu-edigas-BrpNominationAndMatching-NominationResponseDocument-6-1-local-restrictions.xsd"/>
	<!--  restricted codelists  -->
	<!-- Business type-->
	<xsd:simpleType name="StandardRestrictedBusinessCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardBusinessCodeTypeCodeList">
			<xsd:enumeration value="14G"/>
			<xsd:enumeration value="15G"/>
			<xsd:enumeration value="16G"/>
			<xsd:enumeration value="18G"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="BusinessCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedBusinessCodeTypeCodeList LocalRestrictedBusinessCodeTypeCodeList"/>
	</xsd:simpleType>
	<!-- Status type-->
	<xsd:simpleType name="StandardRestrictedStatusCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardStatusCodeTypeCodeList">
			<xsd:enumeration value="06G"/>
			<xsd:enumeration value="07G"/>
			<xsd:enumeration value="08G"/>
			<xsd:enumeration value="09G"/>
			<xsd:enumeration value="10G"/>
			<xsd:enumeration value="11G"/>
			<xsd:enumeration value="12G"/>
			<xsd:enumeration value="13G"/>
			<xsd:enumeration value="14G"/>
			<xsd:enumeration value="35G"/>
			<xsd:enumeration value="36G"/>
			<xsd:enumeration value="37G"/>
			<xsd:enumeration value="67G"/>
			<xsd:enumeration value="72G"/>
			<xsd:enumeration value="73G"/>
			<xsd:enumeration value="74G"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="StatusCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedStatusCodeTypeCodeList LocalRestrictedStatusCodeTypeCodeList"/>
	</xsd:simpleType>	
	<!-- CodingScheme type-->
	<xsd:simpleType name="StandardRestrictedCodingSchemeCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardCodingSchemeCodeTypeCodeList">
			<xsd:enumeration value="305"/>
			<xsd:enumeration value="ZSO"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="CodingSchemeCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedCodingSchemeCodeTypeCodeList LocalRestrictedCodingSchemeCodeTypeCodeList"/>
	</xsd:simpleType>
	<!-- Document type-->
	<xsd:simpleType name="StandardRestrictedDocumentCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardDocumentCodeTypeCodeList">
			<xsd:enumeration value="08G"/>
			<xsd:enumeration value="AND"/>
			<xsd:enumeration value="01G"/>
			<xsd:enumeration value="02G"/>
			<xsd:enumeration value="03G"/>
			<xsd:enumeration value="04G"/>			
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DocumentCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedDocumentCodeTypeCodeList LocalRestrictedDocumentCodeTypeCodeList"/>
	</xsd:simpleType>
	<!-- GasDirection type-->
	<xsd:simpleType name="StandardRestrictedGasDirectionCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardGasDirectionCodeTypeCodeList">
			<xsd:enumeration value="Z02"/>
			<xsd:enumeration value="Z03"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="GasDirectionCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedGasDirectionCodeTypeCodeList LocalRestrictedGasDirectionCodeTypeCodeList"/>
	</xsd:simpleType>
	<!--Nomination type-->
	<xsd:simpleType name="StandardRestrictedNominationCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardNominationCodeTypeCodeList">
			<xsd:enumeration value="A01"/>
			<xsd:enumeration value="A02"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="NominationCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedNominationCodeTypeCodeList LocalRestrictedNominationCodeTypeCodeList"/>
	</xsd:simpleType>
	<!-- QuantityType type-->
	<xsd:simpleType name="StandardRestrictedQuantityCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardQuantityCodeTypeCodeList">
			<xsd:enumeration value="ZXD"/>
			<xsd:enumeration value="ZXE"/>
			<xsd:enumeration value="ZXF"/>
			<xsd:enumeration value="ZXG"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="QuantityCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedQuantityCodeTypeCodeList LocalRestrictedQuantityCodeTypeCodeList"/>
	</xsd:simpleType>
	<!-- Role type-->
	<xsd:simpleType name="StandardRestrictedRoleCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardRoleCodeTypeCodeList">
			<xsd:enumeration value="ZSH"/>
			<xsd:enumeration value="ZUM"/>
			<xsd:enumeration value="ZSO"/>
			<xsd:enumeration value="ZUK"/>			
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RoleCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedRoleCodeTypeCodeList LocalRestrictedRoleCodeTypeCodeList"/>
	</xsd:simpleType>
	<!-- UnitOfMeasure type-->
	<xsd:simpleType name="StandardRestrictedUnitOfMeasureCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardUnitOfMeasureCodeTypeCodeList">
			<xsd:enumeration value="KW1"/>
			<xsd:enumeration value="KW2"/>
			<xsd:enumeration value="A15"/>						
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="UnitOfMeasureCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedUnitOfMeasureCodeTypeCodeList LocalRestrictedUnitOfMeasureCodeTypeCodeList"/>
	</xsd:simpleType>
</xsd:schema>